# Generated by Django 2.2.9 on 2020-02-10 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('university', models.CharField(choices=[('HONGIK', 'HONGIK'), ('KYUNGHEE', 'KYUNGHEE'), ('YONSEI', 'YONSEI')], max_length=30)),
                ('season', models.IntegerField()),
                ('version', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('question_number', models.PositiveSmallIntegerField()),
                ('question_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.QuestionList')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
