# Generated by Django 2.2.9 on 2020-02-21 05:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('university', models.CharField(choices=[('HONGIK', 'HONGIK'), ('KYUNGHEE', 'KYUNGHEE'), ('YONSEI', 'YONSEI')], max_length=30)),
                ('season', models.IntegerField()),
                ('version', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('question_number', models.PositiveSmallIntegerField()),
                ('question_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.QuestionList')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=8, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('age', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(19)])),
                ('height', models.PositiveSmallIntegerField(null=True)),
                ('body_type', models.CharField(choices=[('SKINNY', 'SKINNY'), ('SLIM', 'SLIM'), ('NORMAL', 'NORMAL'), ('CHUBBY', 'CHUBBY'), ('GLAMOROUS', 'GLAMOROUS'), ('FIT', 'FIT')], max_length=10, null=True)),
                ('religion', models.CharField(choices=[('NOTHING', 'NOTHING'), ('CHRISTIANITY', 'CHRISTIANITY'), ('BUDDHISM', 'BUDDHISM'), ('CATHOLIC', 'CATHOLIC'), ('ETC', 'ETC')], max_length=20, null=True)),
                ('is_smoke', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('SOMETIMES', 'SOMETIMES')], max_length=10, null=True)),
                ('campus_location', models.CharField(choices=[('SEOUL', 'SEOUL'), ('INTERNATIONAL', 'INTERNATIONAL'), ('SINCHON', 'SINCHON')], max_length=20, null=True)),
                ('tag', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=100, null=True)),
                ('one_sentence', models.CharField(max_length=300, null=True)),
                ('appearance', models.CharField(max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(120)])),
                ('personality', models.CharField(max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(120)])),
                ('hobby', models.CharField(max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(120)])),
                ('date_style', models.CharField(max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(120)])),
                ('ideal_type', models.CharField(max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(120)])),
                ('chat_link', models.URLField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
