# Generated by Django 2.2.9 on 2020-02-12 08:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=8, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(19)])),
                ('height', models.PositiveSmallIntegerField()),
                ('body_type', models.CharField(choices=[('SKINNY', 'SKINNY'), ('SLIM', 'SLIM'), ('NORMAL', 'NORMAL'), ('CHUBBY', 'CHUBBY'), ('FAT', 'FAT')], max_length=10)),
                ('tag', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
