# Generated by Django 2.2.9 on 2020-02-21 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='appearance',
            field=models.CharField(blank=True, max_length=300, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='body_type',
            field=models.CharField(blank=True, choices=[('SKINNY', 'SKINNY'), ('SLIM', 'SLIM'), ('NORMAL', 'NORMAL'), ('CHUBBY', 'CHUBBY'), ('GLAMOROUS', 'GLAMOROUS'), ('FIT', 'FIT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='campus_location',
            field=models.CharField(blank=True, choices=[('SEOUL', 'SEOUL'), ('INTERNATIONAL', 'INTERNATIONAL'), ('SINCHON', 'SINCHON')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chat_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_style',
            field=models.CharField(blank=True, max_length=300, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobby',
            field=models.CharField(blank=True, max_length=300, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ideal_type',
            field=models.CharField(blank=True, max_length=300, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_smoke',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('SOMETIMES', 'SOMETIMES')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='one_sentence',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personality',
            field=models.CharField(blank=True, max_length=300, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('NOTHING', 'NOTHING'), ('CHRISTIANITY', 'CHRISTIANITY'), ('BUDDHISM', 'BUDDHISM'), ('CATHOLIC', 'CATHOLIC'), ('ETC', 'ETC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
