# Generated by Django 2.2.9 on 2020-02-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200221_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ATTENDING', 'ATTENDING'), ('TAKINGOFF', 'TAKINGOFF')], max_length=10),
            preserve_default=False,
        ),
    ]
