# Generated by Django 2.2.9 on 2020-02-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='scholarly_status',
        ),
    ]
