# Generated by Django 2.2.9 on 2020-02-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200214_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_tempting_word',
            field=models.CharField(max_length=300),
        ),
    ]
