# Generated by Django 2.2.9 on 2020-02-26 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200225_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tag',
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='appearance',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_style',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobby',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ideal_type',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personality',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
    ]
