# Generated by Django 2.2.9 on 2020-02-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200226_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='campus_location',
            field=models.CharField(choices=[('SEOUL', 'SEOUL'), ('INTERNATIONAL', 'INTERNATIONAL'), ('SINCHON', 'SINCHON')], max_length=20),
        ),
    ]
