# Generated by Django 2.2.9 on 2020-03-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200228_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body_type',
            field=models.CharField(blank=True, choices=[('SKINNY', 'SKINNY'), ('SLIM', 'SLIM'), ('SLIMFIT', 'SLIMFIT'), ('NORMAL', 'NORMAL'), ('FIT', 'FIT'), ('CHUBBY', 'CHUBBY')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_smoke',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='one_sentence',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
