# Generated by Django 2.2.9 on 2020-03-11 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200306_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionItem',
        ),
        migrations.DeleteModel(
            name='QuestionList',
        ),
    ]
