# Generated by Django 2.2.9 on 2020-03-12 09:15

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200311_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=profiles.models.profile_image_path),
        ),
    ]
