from model_utils import Choices

UNIVERSITY_CHOICES = Choices('HONGIK', 'KYUNGHEE', 'YONSEI', )

MAP_UNIVERSITY_WITH_CAMPUS = {
    'HONGIK': ['SEOUL'],
    'KYUNGHEE': ['SEOUL', 'INTERNATIONAL'],
    'YONSEI': ['SINCHON', 'INTERNATIONAL'],
}


COIN_CHANGE_REASON = Choices('CONFIRM_USER', 'SELF_DATE_PROFILE_VIEW', 'SELF_DATE_SEND_MESSAGE', )

REWORD_COUNT = {
    'CONFIRM_USER': 30,
}

COST_COUNT = {
    'SELF_DATE_PROFILE_VIEW': 2,
    'SELF_DATE_SEND_MESSAGE': 10,
}
