from model_utils import Choices

UNIVERSITY_CHOICES = Choices('HONGIK', 'KYUNGHEE', 'YONSEI', )

MAP_UNIVERSITY_WITH_CAMPUS = {
    'HONGIK': ['SEOUL'],
    'KYUNGHEE': ['SEOUL', 'INTERNATIONAL'],
    'YONSEI': ['SINCHON', 'INTERNATIONAL'],
}

SIGNUP_REWARD = 30
VIEW_PROFILE_COST = 2
SEND_MESSAGE_COST = 10
