# Generated by Django 2.2.9 on 2020-02-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('university', models.CharField(blank=True, choices=[('HONGIK', 'HONGIK'), ('KYUNGHEE', 'KYUNGHEE'), ('YONSEI', 'YONSEI')], max_length=10, null=True)),
                ('university_email', models.EmailField(blank=True, help_text='학교 인증을 위한 메일', max_length=100)),
                ('is_confirmed_student', models.BooleanField(default=False, help_text='학교 인증을 받았는지 여부')),
                ('user_code', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
