# Generated by Django 2.2.9 on 2020-04-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='campus_location',
            field=models.CharField(choices=[('SEOUL', 'SEOUL'), ('INTERNATIONAL', 'INTERNATIONAL'), ('SINCHON', 'SINCHON'), ('GYEONGSAN', 'GYEONGSAN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, choices=[('HONGIK', 'HONGIK'), ('KYUNGHEE', 'KYUNGHEE'), ('YONSEI', 'YONSEI'), ('YEUNGNAM', 'YEUNGNAM')], max_length=10, null=True),
        ),
    ]
