# Generated by Django 2.2.9 on 2020-04-30 11:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='born_year',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1980), users.models.max_value_current_year], verbose_name='태어난 년도'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='campus_location',
            field=models.CharField(choices=[('SEOUL', 'SEOUL'), ('INTERNATIONAL', 'INTERNATIONAL'), ('SINCHON', 'SINCHON'), ('GYEONGSAN', 'GYEONGSAN')], max_length=20, verbose_name='캠퍼스'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=8, unique=True, verbose_name='공통닉네임'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='scholarly_status',
            field=models.CharField(choices=[('ATTENDING', 'ATTENDING'), ('TAKING_OFF', 'TAKING_OFF')], max_length=10, verbose_name='재학여부'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, choices=[('HONGIK', 'HONGIK'), ('KYUNGHEE', 'KYUNGHEE'), ('YONSEI', 'YONSEI'), ('YEUNGNAM', 'YEUNGNAM')], max_length=10, null=True, verbose_name='학교'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id_card_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=users.models.student_id_card_image_path, verbose_name='학생증 사진'),
        ),
    ]
