# Generated by Django 2.2.9 on 2020-02-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university_email',
            field=models.EmailField(blank=True, help_text='학교 인증을 위한 메일', max_length=100),
        ),
    ]
