# Generated by Django 2.2.9 on 2020-03-19 13:21

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200319_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university_email',
            field=users.models.NullableEmailField(blank=True, help_text='학교 인증을 위한 메일', max_length=100, null=True, unique=True),
        ),
    ]
