# Generated by Django 2.2.9 on 2020-03-21 18:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200319_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id_card_image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=users.models.student_id_card_image_path),
        ),
    ]
