# Generated by Django 2.2.9 on 2020-03-28 15:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import self_date.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfDateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=8, unique=True)),
                ('height', models.PositiveSmallIntegerField(null=True)),
                ('body_type', models.CharField(blank=True, choices=[('SKINNY', 'SKINNY'), ('SLIM', 'SLIM'), ('SLIM_TONED', 'SLIM_TONED'), ('NORMAL', 'NORMAL'), ('BUFF', 'BUFF'), ('CHUBBY', 'CHUBBY')], max_length=10)),
                ('religion', models.CharField(blank=True, choices=[('NOTHING', 'NOTHING'), ('CHRISTIANITY', 'CHRISTIANITY'), ('BUDDHISM', 'BUDDHISM'), ('CATHOLIC', 'CATHOLIC'), ('ETC', 'ETC')], max_length=20)),
                ('is_smoke', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=self_date.models.image_path)),
                ('one_sentence', models.CharField(blank=True, max_length=35)),
                ('appearance', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(120)])),
                ('personality', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(120)])),
                ('hobby', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(120)])),
                ('date_style', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(60)])),
                ('ideal_type', models.CharField(blank=True, max_length=1000, validators=[django.core.validators.MinLengthValidator(120)])),
                ('chat_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
