# Generated by Django 2.2.9 on 2020-03-29 11:34

from django.db import migrations, models
import self_date.models


class Migration(migrations.Migration):

    dependencies = [
        ('self_date', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfdateprofile',
            name='chat_link',
            field=models.URLField(blank=True, validators=[self_date.models.chat_link_validator]),
        ),
    ]
