# Generated by Django 2.2.9 on 2020-04-30 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import self_date.models
import self_date.validators


class Migration(migrations.Migration):

    dependencies = [
        ('self_date', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfdatelike',
            name='liked_self_date_profile',
            field=models.ForeignKey(help_text='like를 받은 사람', on_delete=django.db.models.deletion.CASCADE, related_name='accepted_self_date_likes', to='self_date.SelfDateProfile'),
        ),
        migrations.AlterField(
            model_name='selfdatelike',
            name='self_date_profile',
            field=models.ForeignKey(help_text='like를 보낸 사람', on_delete=django.db.models.deletion.CASCADE, related_name='self_date_likes', to='self_date.SelfDateProfile'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='appearance',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(120)], verbose_name='외모'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='body_type',
            field=models.CharField(choices=[('SLIM', 'SLIM'), ('SLIM_TONED', 'SLIM_TONED'), ('NORMAL', 'NORMAL'), ('BUFF', 'BUFF'), ('CHUBBY', 'CHUBBY')], max_length=10, verbose_name='체형'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='chat_link',
            field=models.URLField(validators=[self_date.validators.chat_link_validator], verbose_name='카카오톡 채팅링크'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='date_style',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(60)], verbose_name='연애관'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='height',
            field=models.PositiveSmallIntegerField(verbose_name='키'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='hobby',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(120)], verbose_name='취미'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='ideal_type',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(120)], verbose_name='이상형'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=self_date.models.image_path, verbose_name='프로필이미지'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='셀프 데이트 프로필 공개 여부'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='is_smoke',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, verbose_name='흡연여부'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='nickname',
            field=models.CharField(max_length=8, unique=True, verbose_name='셀프데이트 닉네임'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='one_sentence',
            field=models.CharField(max_length=35, verbose_name='하고싶은 한마디'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='personality',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(120)], verbose_name='성격'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='프로필'),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='religion',
            field=models.CharField(choices=[('NOTHING', 'NOTHING'), ('CHRISTIANITY', 'CHRISTIANITY'), ('BUDDHISM', 'BUDDHISM'), ('CATHOLIC', 'CATHOLIC'), ('ETC', 'ETC')], max_length=20, verbose_name='종교'),
        ),
    ]
