# Generated by Django 2.2.9 on 2020-02-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200221_1639'),
        ('self_date', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinhistory',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='coinhistory',
            name='reason',
            field=models.CharField(choices=[('SIGNUP', 'SIGNUP'), ('VIEW_PROFILE', 'VIEW_PROFILE'), ('SEND_MESSAGE', 'SEND_MESSAGE')], max_length=50),
        ),
    ]
