# Generated by Django 2.2.9 on 2020-04-17 09:13

import django.core.validators
from django.db import migrations, models
import self_date.validators


class Migration(migrations.Migration):

    dependencies = [
        ('self_date', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfdateprofile',
            name='appearance',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='body_type',
            field=models.CharField(choices=[('SKINNY', 'SKINNY'), ('SLIM', 'SLIM'), ('SLIM_TONED', 'SLIM_TONED'), ('NORMAL', 'NORMAL'), ('BUFF', 'BUFF'), ('CHUBBY', 'CHUBBY')], max_length=10),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='chat_link',
            field=models.URLField(validators=[self_date.validators.chat_link_validator]),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='date_style',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(60)]),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='height',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='hobby',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='ideal_type',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='is_smoke',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='one_sentence',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='personality',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='religion',
            field=models.CharField(choices=[('NOTHING', 'NOTHING'), ('CHRISTIANITY', 'CHRISTIANITY'), ('BUDDHISM', 'BUDDHISM'), ('CATHOLIC', 'CATHOLIC'), ('ETC', 'ETC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='selfdateprofile',
            name='tags',
            field=models.CharField(max_length=500),
        ),
    ]
