# Generated by Django 2.2.9 on 2020-04-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_date', '0002_auto_20200417_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfdateprofile',
            name='body_type',
            field=models.CharField(choices=[('SLIM', 'SLIM'), ('SLIM_TONED', 'SLIM_TONED'), ('NORMAL', 'NORMAL'), ('BUFF', 'BUFF'), ('CHUBBY', 'CHUBBY')], max_length=10),
        ),
    ]
