# Generated by Django 2.2.9 on 2020-04-02 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_coinhistory_message'),
        ('self_date', '0002_auto_20200329_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfDateProfileRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buying_self_date_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_self_date_rights', to='self_date.SelfDateProfile')),
                ('coin_history', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='coins.CoinHistory')),
                ('target_self_date_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_self_date_rights', to='self_date.SelfDateProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
