# Generated by Django 2.2.9 on 2020-04-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_date', '0002_auto_20200430_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfdateprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_date_profile', to='users.Profile', verbose_name='프로필'),
        ),
        migrations.AlterField(
            model_name='selfdateprofileright',
            name='buying_self_date_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_self_date_profile_rights', to='self_date.SelfDateProfile'),
        ),
        migrations.AlterField(
            model_name='selfdateprofileright',
            name='target_self_date_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_self_date_profile_rights', to='self_date.SelfDateProfile'),
        ),
    ]
