# Generated by Django 2.2.9 on 2020-04-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_date', '0003_selfdateprofileright'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfdateprofileright',
            name='right_type',
            field=models.CharField(choices=[('CONFIRM_USER', 'CONFIRM_USER'), ('SELF_DATE_PROFILE_VIEW', 'SELF_DATE_PROFILE_VIEW'), ('SELF_DATE_SEND_MESSAGE', 'SELF_DATE_SEND_MESSAGE')], max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selfdateprofileright',
            name='coin_history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='coins.CoinHistory'),
        ),
    ]
