# Generated by Django 2.2.9 on 2020-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_date', '0003_auto_20200228_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinhistory',
            name='rest_coin',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
