# Generated by Django 2.2.9 on 2020-03-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_date', '0004_auto_20200303_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinhistory',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.Profile'),
        ),
    ]
