# Generated by Django 2.2.9 on 2020-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinhistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='coinhistory',
            name='reason',
            field=models.CharField(choices=[('CONFIRM_USER', 'CONFIRM_USER'), ('SELF_DATE_PROFILE_VIEW', 'SELF_DATE_PROFILE_VIEW'), ('SELF_DATE_SEND_MESSAGE', 'SELF_DATE_SEND_MESSAGE')], max_length=50),
        ),
    ]
