# Generated by Django 2.2.9 on 2020-03-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20200331_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinhistory',
            name='message',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
