# Generated by Django 2.2.9 on 2020-04-02 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_coinhistory_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinhistory',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
