# Generated by Django 2.2.9 on 2020-04-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_auto_20200403_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinhistory',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin_histories', to='users.Profile'),
        ),
    ]
